pub const STATE_LEN_RESERVED: u64 = 1024 * 1024 * 4;
pub const STATE_OFFSETOF_AVAILABLE_HEAD: u64 = 0;
pub const STATE_OFFSETOF_INVISIBLE_HEAD: u64 = STATE_OFFSETOF_AVAILABLE_HEAD + 8;
pub const STATE_OFFSETOF_VACANT_HEAD: u64 = STATE_OFFSETOF_INVISIBLE_HEAD + 8;
pub const STATE_OFFSETOF_FRONTIER: u64 = STATE_OFFSETOF_VACANT_HEAD + 8;

pub const SLOTS_OFFSET_START: u64 = STATE_LEN_RESERVED;
pub const SLOT_LEN_MAX: u64 = 1024;
pub const SLOT_OFFSETOF_CREATED_TS: u64 = 0;
pub const SLOT_OFFSETOF_VISIBLE_TS: u64 = SLOT_OFFSETOF_CREATED_TS + 8;
pub const SLOT_OFFSETOF_POLL_COUNT: u64 = SLOT_OFFSETOF_VISIBLE_TS + 8;
pub const SLOT_OFFSETOF_NEXT: u64 = SLOT_OFFSETOF_POLL_COUNT + 4;
pub const SLOT_OFFSETOF_LEN: u64 = SLOT_OFFSETOF_NEXT + 8;
pub const SLOT_OFFSETOF_CONTENTS: u64 = SLOT_OFFSETOF_LEN + 2;
pub const SLOT_FIXED_FIELDS_LEN: u64 = SLOT_OFFSETOF_CONTENTS;
pub const MESSAGE_SLOT_CONTENT_LEN_MAX: u64 = SLOT_LEN_MAX - SLOT_FIXED_FIELDS_LEN;
