pub const STATE_LEN_RESERVED: usize = 1024 * 1024 * 4;
pub const STATE_OFFSETOF_AVAILABLE_HEAD: usize = 0;
pub const STATE_OFFSETOF_INVISIBLE_HEAD: usize = STATE_OFFSETOF_AVAILABLE_HEAD + 8;
pub const STATE_OFFSETOF_VACANT_HEAD: usize = STATE_OFFSETOF_INVISIBLE_HEAD + 8;

pub const SLOTS_OFFSET_START: usize = STATE_LEN_RESERVED;
pub const SLOT_LEN_MAX: usize = 1024;
pub const SLOT_OFFSETOF_CREATED_TS: usize = 0;
pub const SLOT_OFFSETOF_VISIBLE_TS: usize = SLOT_OFFSETOF_CREATED_TS + 8;
pub const SLOT_OFFSETOF_POLL_COUNT: usize = SLOT_OFFSETOF_VISIBLE_TS + 8;
pub const SLOT_OFFSETOF_NEXT: usize = SLOT_OFFSETOF_POLL_COUNT + 4;
pub const SLOT_OFFSETOF_LEN: usize = SLOT_OFFSETOF_NEXT + 8;
pub const SLOT_OFFSETOF_CONTENTS: usize = SLOT_OFFSETOF_LEN + 2;
pub const SLOT_FIXED_FIELDS_LEN: usize = SLOT_OFFSETOF_CONTENTS;
pub const MESSAGE_SLOT_CONTENT_LEN_MAX: usize = SLOT_LEN_MAX - SLOT_FIXED_FIELDS_LEN;
